// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetNavDatasResponse, CreateNavDataResponse } from './types.gen';

/**
 * 获取导航数据
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const getNavDatas = (): CancelablePromise<GetNavDatasResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/v1/nav_datas'
}); };

/**
 * Create Nav Data
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const createNavData = (): CancelablePromise<CreateNavDataResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/v1/nav_datas'
}); };