// This file is auto-generated by @hey-api/openapi-ts

export type GetNavDatasResponse = unknown;

export type CreateNavDataResponse = unknown;

export type $OpenApiTs = {
    '/api/v1/nav_datas': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};