// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginUser = {
    name: string;
    password: string;
};

export type Order = {
    id: number;
    order_no?: string;
    user_id: number;
    created_at?: string;
    pay_status?: PayStatus;
    pay_amount?: number;
    pay_time?: string;
    status?: OrderStatus;
    product_snap_image: string;
    product_snap_name: string;
    product_snap_price: number;
    product_snap_description: string;
    product_id: number;
};

export type OrderStatus = 'normal' | 'cancel';

export type PayStatus = 'pending' | 'success';

export type Product = {
    id: number;
    image: string;
    name: string;
    price: number;
    description: string;
    sold?: number;
    status?: ProductStatus;
};

export type ProductIn = {
    name: string;
    image?: string | null;
    price: number;
    description?: string | null;
};

export type ProductStatus = 'active' | 'offline';

export type RegisterUser = {
    name: string;
    password: string;
    ensure_password: string;
};

export type UserOut = {
    name: string;
    id: number;
    email: string | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Wallet = {
    id: number;
    user_id: number;
    balance?: number;
};

export type GetNavDatasResponse = unknown;

export type CreateNavDataResponse = unknown;

export type RegisterData = {
    requestBody: RegisterUser;
};

export type RegisterResponse = UserOut;

export type LoginData = {
    requestBody: LoginUser;
};

export type LoginResponse = UserOut;

export type LogoutResponse = unknown;

export type GetUserInfoResponse = UserOut;

export type GetProductsResponse = Array<Product>;

export type CreateProductData = {
    requestBody: ProductIn;
};

export type CreateProductResponse = Product;

export type GetOrdersResponse = Array<Order>;

export type CreateOrderData = {
    productId: number;
};

export type CreateOrderResponse = Order;

export type UpdateOrderPayStatusData = {
    orderNo: string;
    payStatus: PayStatus;
};

export type UpdateOrderPayStatusResponse = Order;

export type GetWalletResponse = Wallet;

export type $OpenApiTs = {
    '/api/v1/nav_datas': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/v1/auth/register': {
        post: {
            req: RegisterData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserOut;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/auth/login': {
        post: {
            req: LoginData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserOut;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/auth/logout': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/v1/auth/userinfo': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserOut;
            };
        };
    };
    '/api/v1/shop/products': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Product>;
            };
        };
        post: {
            req: CreateProductData;
            res: {
                /**
                 * Successful Response
                 */
                200: Product;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/shop/orders': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Order>;
            };
        };
        post: {
            req: CreateOrderData;
            res: {
                /**
                 * Successful Response
                 */
                200: Order;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/shop/order_pay_status/{order_no}': {
        put: {
            req: UpdateOrderPayStatusData;
            res: {
                /**
                 * Successful Response
                 */
                200: Order;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/shop/wallet': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Wallet;
            };
        };
    };
};